apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: collaborators.github.internal.lab.dev
spec:
  group: github.internal.lab.dev
  names:
    kind: Collaborator
    listKind: CollaboratorList
    plural: collaborators
    singular: collaborator
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              team:
                type: string
              repository:
                type: string
              membership:
                enum:
                - Pull
                - Push
                - Admin
                type: string
              organizationNamespace:
                type: string
            required:
            - team
            - repository
            - organizationNamespace
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
