apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: discords.lab.dev
spec:
  group: lab.dev
  names:
    kind: Discord
    listKind: DiscordList
    plural: discords
    singular: discord
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              credentialsReference:
                nullable: true
                properties:
                  name:
                    type: string
                  namespaceProperty:
                    type: string
                type: object
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              guild:
                format: int64
                type: integer
              credentials:
                nullable: true
                type: string
            required:
            - credentials
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
