apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.lab.dev
spec:
  group: lab.dev
  names:
    kind: Environment
    listKind: EnvironmentList
    plural: environments
    singular: environment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: the type of environment this is
      jsonPath: .spec.type
      name: Type
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              type:
                description: the type of environment this is
                enum:
                - Production
                - PreProduction
                - Engineering
                type: string
            required:
            - type
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
