apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: githubs.lab.dev
spec:
  group: lab.dev
  names:
    kind: Github
    listKind: GithubList
    plural: githubs
    singular: github
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: the github organisation
      jsonPath: .spec.organisation
      name: Organisation
      priority: 0
      type: string
    - description: >-
        the global team which everyone will be part of, this is so

        everyone can get access to private repo's
      jsonPath: .spec.globalTeam
      name: GlobalTeam
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              credentialsReference:
                nullable: true
                properties:
                  name:
                    type: string
                  namespaceProperty:
                    type: string
                type: object
              id:
                format: int32
                nullable: true
                type: integer
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              organisation:
                description: the github organisation
                type: string
              credentials:
                description: API key to call the Github API with
                type: string
              archive:
                description: 'when services are deleted should the code be archived (Default: true)'
                type: boolean
              visibility:
                description: 'the default visibility of all repositories (Default: private)'
                enum:
                - Public
                - Internal
                - Private
                type: string
              globalTeam:
                description: >-
                  the global team which everyone will be part of, this is so

                  everyone can get access to private repo's
                type: string
              archiveTeam:
                description: >-
                  the team which is used to admin archived projects

                  (to make github as clean as it can be for others)
                type: string
              cleanUp:
                description: >-
                  remove all managed items when deleted.

                  (remove teams, repos, including archived)
                type: boolean
              technicalUser:
                description: the technical user which will be used to modify github with
                type: string
            required:
            - organisation
            - credentials
            - technicalUser
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
