apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubernetess.lab.dev
spec:
  group: lab.dev
  names:
    kind: Kubernetes
    listKind: KubernetesList
    plural: kubernetess
    singular: kubernetes
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              clusterId:
                type: string
              environment:
                type: string
              cloud:
                type: string
              zone:
                type: string
              region:
                type: string
              isProduction:
                type: boolean
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              isPrimary:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
