apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: members.lab.dev
spec:
  group: lab.dev
  names:
    kind: Member
    listKind: MemberList
    plural: members
    singular: member
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.role
      name: Role
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              account:
                type: string
              role:
                enum:
                - Owner
                - Member
                - Guest
                type: string
            required:
            - account
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
