apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organizations.lab.dev
spec:
  group: lab.dev
  names:
    kind: Organization
    listKind: OrganizationList
    plural: organizations
    singular: organization
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              retainFor:
                format: int32
                type: integer
              productionAccessWorkFlow:
                type: boolean
              productionName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
