apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organizations.lab.dev
spec:
  group: lab.dev
  names:
    kind: Organization
    listKind: OrganizationList
    plural: organizations
    singular: organization
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              retainFor:
                description: >-
                  how long to retain the service, when it have been deleted

                  this allows for a service to be transferred between tenancies (default 1 week)
                format: int32
                type: integer
              productionAccessWorkFlow:
                type: boolean
              engineering:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
