apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organisations.lab.dev
spec:
  group: lab.dev
  names:
    kind: Organisation
    listKind: OrganisationList
    plural: organisations
    singular: organisation
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              service:
                properties:
                  retainFor:
                    format: int32
                    type: integer
                  productionAccessWorkFlow:
                    type: boolean
                  productionName:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
