apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.internal.lab.dev
spec:
  group: internal.lab.dev
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              name:
                nullable: true
                type: string
              cluster:
                nullable: true
                type: string
              ownedBy:
                nullable: true
                type: string
            required:
            - name
            - cluster
            - ownedBy
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              name:
                nullable: true
                type: string
              cluster:
                nullable: true
                type: string
              ownedBy:
                nullable: true
                type: string
            required:
            - name
            - cluster
            - ownedBy
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
