apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.rancher.internal.lab.dev
spec:
  group: rancher.internal.lab.dev
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              id:
                description: the rancher project id (as it get generated, and placed into another namespace)
                nullable: true
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              tenancy:
                description: the name of the tenancy (not the name of this resource)
                type: string
              kubernetes:
                description: the cluster this belongs too
                type: string
            required:
            - tenancy
            - kubernetes
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
