apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ranchers.lab.dev
spec:
  group: lab.dev
  names:
    kind: Rancher
    listKind: RancherList
    plural: ranchers
    singular: rancher
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              technicalUser:
                description: >-
                  this user will be assigned as the owner in a number of cases.

                  should be a GOD user.
                type: string
              globalDefaultRole:
                description: the default role to set everyone to, by default user-base is seen to be more secure
                type: string
              globalOrganizationRole:
                type: string
              globalZoneMemberRole:
                type: string
              globalZoneFireFighterMemberRole:
                type: string
              clusterZoneMemberRole:
                type: string
              clusterProductionZoneMemberRole:
                type: string
              clusterZoneFireFighterMemberRole:
                type: string
              clusterTenancyMemberRole:
                type: string
              clusterProductionTenancyMemberRole:
                type: string
              tenancyMemberRole:
                type: string
              tenancyProductionMemberRole:
                type: string
              tenancyFireFighterMemberRole:
                type: string
              tenancyGuestRole:
                type: string
              platformMemberRole:
                type: string
              platformProductionMemberRole:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
