apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositorys.github.internal.lab.dev
spec:
  group: github.internal.lab.dev
  names:
    kind: Repository
    listKind: RepositoryList
    plural: repositorys
    singular: repository
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              id:
                format: int64
                nullable: true
                type: integer
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              visibility:
                description: control who can see the repository
                enum:
                - Public
                - Internal
                - Private
                type: string
              state:
                description: is the repository is active or archived
                enum:
                - Archived
                - Active
                type: string
              type:
                description: >-
                  the repo can be for projects/service (normal) or to adminsitrate/control (system)

                  [default: Normal]
                enum:
                - System
                - Normal
                type: string
              enforceCollaborators:
                description: >-
                  ensure only the managed collaborators are provided access.

                  [default: false]
                type: boolean
              organizationNamespace:
                type: string
            required:
            - organizationNamespace
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
