apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teams.github.internal.lab.dev
spec:
  group: github.internal.lab.dev
  names:
    kind: Team
    listKind: TeamList
    plural: teams
    singular: team
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              id:
                format: int32
                nullable: true
                type: integer
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              visibility:
                enum:
                - Public
                - Internal
                - Private
                type: string
              type:
                enum:
                - System
                - Normal
                type: string
              description:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
