apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teammembers.github.internal.lab.dev
spec:
  group: github.internal.lab.dev
  names:
    kind: TeamMember
    listKind: TeamMemberList
    plural: teammembers
    singular: teammember
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              login:
                type: string
              team:
                type: string
            required:
            - login
            - team
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
