apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenancys.lab.dev
spec:
  group: lab.dev
  names:
    kind: Tenancy
    listKind: TenancyList
    plural: tenancys
    singular: tenancy
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              isPlatform:
                type: boolean
              clusterFilter:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
