apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenancycontexts.internal.lab.dev
spec:
  group: internal.lab.dev
  names:
    kind: TenancyContext
    listKind: TenancyContextList
    plural: tenancycontexts
    singular: tenancycontext
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              organizationNamespace:
                type: string
            required:
            - organizationNamespace
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
