apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenancys.lab.dev
spec:
  group: lab.dev
  names:
    kind: Tenancy
    listKind: TenancyList
    plural: tenancys
    singular: tenancy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: this indicates that the team is a platform team
      jsonPath: .spec.isPlatform
      name: IsPlatform
      priority: 0
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              isPlatform:
                description: this indicates that the team is a platform team
                type: boolean
              zoneFilter:
                description: this will be used to select which zones a tenancy has access to
                items:
                  properties:
                    key:
                      type: string
                    operator:
                      enum:
                      - Pattern
                      - StartsWith
                      - Equals
                      - NotEquals
                      type: string
                    value:
                      type: string
                  required:
                  - key
                  - operator
                  - value
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
