apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zones.lab.dev
spec:
  group: lab.dev
  names:
    kind: Zone
    listKind: ZoneList
    plural: zones
    singular: zone
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              isProduction:
                type: boolean
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              environment:
                type: string
              cloud:
                type: string
              region:
                type: string
            required:
            - environment
            - cloud
            - region
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
