apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zones.lab.dev
spec:
  group: lab.dev
  names:
    kind: Zone
    listKind: ZoneList
    plural: zones
    singular: zone
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: the name of the environment this belongs to
      jsonPath: .spec.environment
      name: Environment
      priority: 0
      type: string
    - description: aws, azure, on-prem, scaleway, etc
      jsonPath: .spec.cloud
      name: Cloud
      priority: 0
      type: string
    - description: where this zone is located
      jsonPath: .spec.region
      name: Region
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              type:
                enum:
                - Production
                - PreProduction
                - Engineering
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              environment:
                description: the name of the environment this belongs to
                type: string
              cloud:
                description: aws, azure, on-prem, scaleway, etc
                type: string
              region:
                description: where this zone is located
                type: string
              isControl:
                description: denotes is this cluster is where rancher is running
                type: boolean
            required:
            - environment
            - cloud
            - region
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
