apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zoneattributes.lab.dev
spec:
  group: lab.dev
  names:
    kind: ZoneAttribute
    listKind: ZoneAttributeList
    plural: zoneattributes
    singular: zoneattribute
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties: {}
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties: {}
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
