apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - github.internal.lab.dev
  - lab.dev
  - coordination.k8s.io
  resources:
  - collaborators
  - accounts
  - tenancys
  - teammembers
  - users
  - githubs
  - repositorys
  - teams
  - firefighters
  - ranchers
  - members
  - leases
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - github.internal.lab.dev
  resources:
  - collaborators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - tenancys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.internal.lab.dev
  resources:
  - teammembers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.internal.lab.dev
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - githubs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.internal.lab.dev
  resources:
  - repositorys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.internal.lab.dev
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - firefighters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - ranchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lab.dev
  resources:
  - members/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
